[
  {
    id: 15,
    tipo: "tienda afiliada",
    producto: "1,3",
    producto_pavo: "1",
    producto_cerdo: "2",
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Ate/Salamanca",
    tipo_ubicacion: "Lima",
    nombre: "KHILIN PERU",
    direccion: "Av. Los Paracas 162",
    telefono: "(01) 435 7916 / 952 952 441",
    horario:
      "Lunes a S\u00e1bado de 8:30 a.m. a 7:00 p.m. Domingo 8:30 am a 2:30 p.m",
    restricciones:
      "Se atiende vale f\u00edsico y digital por pavo y cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tienda-salamanca-Khilin.webp",
    urlfoto: "/images/puntoscanje/Tienda-salamanca-Khilin.webp",
    urlmapa: "upload/qR2EqpkA9dXaImWvXwpQB1WMOHB4uRqNUoh6nGfs.png",
    url_tienda_jpg: "upload/hOG4qHH3DhSg6bxXK3jkKHHeor8JPWEyHJoufjnu.png",
    url_tienda_webp: "upload/EcFpSq48Dvr5bhbPNsYIzmbJjjvWucK6sTvDC3tJ.webp",
    latitud: "-12.07594879",
    longitud: "-76.98828081",
    estado: 1,
    id_seguimiento: "tienda-afiliada-ate-salamanca-khilin-peru",
    aceptareactivacion: 0,
  },
  {
    id: 8,
    tipo: "tienda afiliada",
    producto: "1,3",
    producto_pavo: "1",
    producto_cerdo: "2",
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Carabayllo",
    tipo_ubicacion: "Lima",
    nombre: "AVICOLA LAM",
    direccion: "Jr. Amarantos 122, Urb. Sta. Isabel",
    telefono: "543 6003 / 527 8567",
    horario: "De Lunes a S\u00e1bado de 6:30 a.m. a 3:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico y digital por pavo y cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tienda-Carabayllo-Avicola-Lam.webp",
    urlfoto: "/images/puntoscanje/Tienda-Carabayllo-Avicola-Lam.webp",
    urlmapa: "upload/bWM7d7q5Yf6pDtN4BE7i9Zb6iF9nsQgipggQowmx.png",
    url_tienda_jpg: "upload/Aa0mJMClJnky3WMy1qxgrpDJk3K7PewINpk6bbWP.png",
    url_tienda_webp: "upload/J8mJfZI4WnoTZ7p54aKE4rnYxlq2pPvDveClNKjz.webp",
    latitud: "-11.8998377986681",
    longitud: "-77.03674105",
    estado: 1,
    id_seguimiento: "tienda-afiliada-carabayllo-avicola-lam",
    aceptareactivacion: 1,
  },
  {
    id: 9,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Chorrillos",
    tipo_ubicacion: "Lima",
    nombre: "CASTELLARES ARAMBURU MARISOL",
    direccion:
      "Jr. Justo Naveda Nro. 136 (entre la cuadra 5 Y 6 de la Av. Huaylas)",
    telefono: "(01) 251 5034",
    horario:
      "De Lunes a S\u00e1bado de 8:30 a.m. a 8:00 p.m. Domingo de 9:00 am - 2:00 pm",
    restricciones:
      "Se atiende vale f\u00edsico y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tienda-Chorrillos-Marisol-Castellares.webp",
    urlfoto: "/images/puntoscanje/Tienda-Chorrillos-Marisol-Castellares.webp",
    urlmapa: "upload/ChgQXx9pClSbTpvUvlalWDxEJRqcnJnoiAF6q6pk.png",
    url_tienda_jpg: "upload/YtDg4N8yTNGLf9FIpbpMdqegmtcazHvUJzsi7wCP.png",
    url_tienda_webp: "upload/YM3LoBipTgExZZ4mahmruA0ebeXnmTGttpLm8QYf.webp",
    latitud: "-12.16997889",
    longitud: "-77.02392449",
    estado: 1,
    id_seguimiento: "tienda-afiliada-chorrillos-castellares-aramburu-marisol",
    aceptareactivacion: 0,
  },
  {
    id: 103,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Chorrillos",
    tipo_ubicacion: "Lima",
    nombre: "COMERCIALIZADORA DE ALIMENTOS M\u00c1S",
    direccion: "Av. Alameda Sur 1156",
    telefono: "991-803-876",
    horario:
      "De Lunes a S\u00e1bado de 8:00 am a 8:00 pm. Domingo de 8:00 am a 2:00 pm.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/qtAI11JKcflTiE66Z8OyZ0m0RHFpf98aaFs0tvXo.png",
    url_tienda_jpg: "upload/gdXmM84jCBSTRUqqFldZIiHO8HMqprt7LeTqbLhF.png",
    url_tienda_webp: "upload/fnPdQkuchLYckbY59ACjXrwwAudzZ8LL2NhdZAWh.webp",
    latitud: "-12.2035123",
    longitud: "-77.0161291",
    estado: 1,
    id_seguimiento:
      "tienda-afiliada-chorrillos-comercializadora-de-alimentos-mas",
    aceptareactivacion: 0,
  },
  {
    id: 10,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Comas",
    tipo_ubicacion: "Lima",
    nombre: "GRUPO VERTIZ SAC",
    direccion: "Av. Universitaria 6951 Urb. Santa Luzmila",
    telefono: "912-368-760 / (01) 496 4733",
    horario: "De Lunes a S\u00e1bado de 8:30 a.m. a 7:30 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tienda-Comas.webp",
    urlfoto: "/images/puntoscanje/Tienda-Comas.webp",
    urlmapa: "upload/qIRVMPF4ercYSfLrvK1vlVV0W9YlQ4AzsH6RJf1Z.png",
    url_tienda_jpg: "upload/o4ZrgOL15TF1OrMWzIwJ2frCFjGZ03OErx0UR2VR.png",
    url_tienda_webp: "upload/WQN2KkbjCYyDFc4hyMfGMcTjHdarozUPIjhFGiVE.webp",
    latitud: "-11.94062862",
    longitud: "-77.05982322",
    estado: 1,
    id_seguimiento: "tienda-afiliada-comas-grupo-vertiz-sac",
    aceptareactivacion: 0,
  },
  {
    id: 101,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Huaura",
    tipo_ubicacion: "Lima",
    nombre: "DISTRIBUCIONES MERCONOR",
    direccion: "Jiron Atahualpa 364, Huacho 15137, Per\u00fa",
    telefono: "924 985 979",
    horario:
      "De Lunes a Viernes de 9:00 a.m. a 1:00 p.m. y de 4:00 p.m.a 5:00 p.m.",
    restricciones: "-",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/icrH6IHYZ0zSGedue2ycsI32YIsq2gS7253DL5he.png",
    url_tienda_jpg: null,
    url_tienda_webp: null,
    latitud: "-11.1042216",
    longitud: "-77.6101042",
    estado: 1,
    id_seguimiento: "DAP- MERCONOR -HUACHO",
    aceptareactivacion: 0,
  },
  {
    id: 89,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Jesus Maria",
    tipo_ubicacion: "Lima",
    nombre: "CORTEZ VELIZ JUAN CARLOS",
    direccion: "RES. SAN FELIPE NRO. SN INT. 30 CENTRO COMERCIAL SAN FELIPE",
    telefono: "(01) 460 3277",
    horario: "Lunes a S\u00e1bado de 1:30 am a 6:00 pm",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/RKflcKSmDdNHdv5zMMEzN5834a215rbjjNB0HHwr.png",
    url_tienda_jpg: "upload/nOEcyADzgu2eQ9Zk2bUipkRIH1THCa40eCxHPj1k.jpeg",
    url_tienda_webp: "upload/uPlycrGihTO9FO9PiJoHZkOIyQYCkY0ttjv6zH9q.webp",
    latitud: "-12.08785653255235",
    longitud: "-77.0539390031105",
    estado: 1,
    id_seguimiento: "tienda-afiliada-jesus-maria-cortez-veliz-juan-carlos",
    aceptareactivacion: 0,
  },
  {
    id: 92,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "La Molina",
    tipo_ubicacion: "Lima",
    nombre: "GROUP ONE SAC - CONSTRUCTORES",
    direccion:
      "AV. DE LOS CONSTRUCTORES NRO. 875 URB. SANTA RAQUEL ZONA OESTE ET. UNO",
    telefono: "947-259-972",
    horario:
      "De Lunes a S\u00e1bado de 8:00 a.m. a 9:00 p.m. Domingo de 8:00 am a 5:00 p.m",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/eovEepZh3dEH8XmH2UcHxgCzNYb2wixbLdlRELGn.png",
    url_tienda_jpg: "upload/gknl9JUuWoAzItGpk8Tw3t3BAlF2CRU0fxR57ozq.jpeg",
    url_tienda_webp: "upload/tmTl6ULmMMFEJzj1oYWYARapkiNY9SBV4vh2KPU3.webp",
    latitud: "-12.06283474",
    longitud: "-76.94924164",
    estado: 1,
    id_seguimiento: "tienda-afiliada-la-molina-group-one-sac-constructores",
    aceptareactivacion: 0,
  },
  {
    id: 11,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "La Victoria",
    tipo_ubicacion: "Lima",
    nombre: "MARKET APOLO",
    direccion: "Jr. 3 de Febrero 1247 Urb. Apolo",
    telefono: "(01) 512 8624 / 998-281-005",
    horario:
      "De Lunes a Domingo de 8:00 a.m. a 8:00 p.m. Domingo de 8:00 am a 2:00 p.m",
    restricciones:
      "Se atiende vale f\u00edsico y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tienda-La-Victoria-Apolo.webp",
    urlfoto: "/images/puntoscanje/Tienda-La-Victoria-Apolo.webp",
    urlmapa: "upload/tZY43Fk33n1HGaovgS5OPcpMiYTkAuMWJ7vcLO6F.png",
    url_tienda_jpg: "upload/NxAnTazvv1ufMYLp9KmAEBIZgzYDJJBLLTsA053G.png",
    url_tienda_webp: "upload/AzdJIkvjxgRvJA2CvMktMrX0AemxTxoTWSDZzi2R.webp",
    latitud: "-12.07292384",
    longitud: "-77.00904704",
    estado: 1,
    id_seguimiento: "tienda-afiliada-la-victoria-market-polo",
    aceptareactivacion: 0,
  },
  {
    id: 12,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Lince",
    tipo_ubicacion: "Lima",
    nombre: "E Y J I.R.L",
    direccion: "Av. Petit Thouars 2260",
    telefono: "(01) 471 6212",
    horario: "Lunes a S\u00e1bado de 8:00 a.m. a 4:30 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tienda-Lince-E_J-1.webp",
    urlfoto: "/images/puntoscanje/Tienda-Lince-E_J-1.webp",
    urlmapa: "upload/cBAHfbP75YpbLT3JVptx7EGcq72oCIyoalEyqRJL.png",
    url_tienda_jpg: "upload/4wtfzLRqe4Dj7MuA6MIc7TRBuNRFsk6rGp3yTRCz.png",
    url_tienda_webp: "upload/v50GDP2XapJ7VmBMWM4xo17DIPIXF6pLgXb8qXjP.webp",
    latitud: "-12.08658009",
    longitud: "-77.03305515",
    estado: 1,
    id_seguimiento: "tienda-afiliada-lince-e-y-j-irl",
    aceptareactivacion: 0,
  },
  {
    id: 86,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Magdalena del Mar",
    tipo_ubicacion: "Lima",
    nombre: "ARIDEL PERU EIRL",
    direccion: "JR. GENERAL JOSE DE SAN MARTIN 480 URB. ORBEA",
    telefono: "972662130",
    horario: "De Lunes a S\u00e1bado de 9:00 a.m. a 7:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/NCsHdeSkz6ncI7mLp2rqV0kajXUHeeisNxqKin7I.png",
    url_tienda_jpg: "upload/lefPvtyKzdikF0yv014B2AiBeBm5jCt8CkZmRda7.jpeg",
    url_tienda_webp: "upload/iaR8wTrwWrzR9zCzV6sQ7zfWP9pZVg1W6mfYhbqR.webp",
    latitud: "-12.0900965",
    longitud: "-77.0707007",
    estado: 1,
    id_seguimiento: "tienda-afiliada-magdalena-del-mar-aridel-peru-eirl",
    aceptareactivacion: 0,
  },
  {
    id: 14,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Pueblo Libre",
    tipo_ubicacion: "Lima",
    nombre: "NUTRIABASTOS E.I.R.L.",
    direccion: "Av. Bolivar Nro. 1149",
    telefono: "(01) 261 0008",
    horario: "De Lunes a S\u00e1bado de 8:00 am a 4:30 pm",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tienda-Bolivar-(Pueblo-Libre)-Nutriabastos.webp",
    urlfoto:
      "/images/puntoscanje/Tienda-Bolivar-(Pueblo-Libre)-Nutriabastos.webp",
    urlmapa: "upload/QCZPHQnhnoQqzGosHrXtA6ocATmcXugAUtJpJq9z.png",
    url_tienda_jpg: "upload/xsebnb05NoypqMoiJwgi7pSvYlvE9jCCSeXoGcnV.png",
    url_tienda_webp: "upload/jPm8fAX8fyZ5sgqZcj27HRa3tVbnPQvcKIQfTUJR.webp",
    latitud: "-12.07248131",
    longitud: "-77.06535686",
    estado: 1,
    id_seguimiento: "tienda-afiliada-pueblo-libre-nutriabastos-eirl",
    aceptareactivacion: 0,
  },
  {
    id: 99,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Puente Piedra",
    tipo_ubicacion: "Lima",
    nombre: "CHIMU AGROPECUARIA",
    direccion:
      "Av. San Juan de Dios MZ F Lote 6. Urbanizaci\u00f3n Las Vegas, Puente Piedra.",
    telefono: "01- 4803493",
    horario: "Lunes a S\u00e1bado 7:00 a.m. a 3:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico y digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/Y6SIZPeHtOIn2CQgJo5thKmznCHSqtfYELYL2Vui.png",
    url_tienda_jpg: null,
    url_tienda_webp: "upload/nIqWERPWhzQX6oVxi8QruUHtxkzPx2o7lIicnX3Y.jpeg",
    latitud: "-11.864414781540093",
    longitud: "-77.06623106239626",
    estado: 1,
    id_seguimiento: "Afiliada-Puente-Piedra",
    aceptareactivacion: 0,
  },
  {
    id: 87,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "San Borja",
    tipo_ubicacion: "Lima",
    nombre: "FOURNIER & SAAVEDRA S.A.C.",
    direccion: "AV. AVIACI\u00d3N 3431",
    telefono: "971-968-809",
    horario:
      "Lunes a S\u00e1bado de 7:00 am a 10:00 pm. Domingo de 8:00 am - 10:00 pm",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/PZcuOK7eOEkhWLohXRJxxPHBZlO33XODjP83wf9d.png",
    url_tienda_jpg: "upload/MKO8xA7V0yNBredjnsd5OnPP4YpC1xTB8pz17TW3.jpeg",
    url_tienda_webp: "upload/8fDZvmahce7i4NAeSpvlhQ7vf5iZQCvsYDhAcynQ.webp",
    latitud: "-12.1060264",
    longitud: "-77.0007901",
    estado: 1,
    id_seguimiento: "tienda-afiliada-san-borja-fournier-&-saavedra-sac",
    aceptareactivacion: 0,
  },
  {
    id: 76,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "San Juan de Lurigancho",
    tipo_ubicacion: "Lima",
    nombre: "CARNICERIA NARCISA",
    direccion:
      "AV. GRAN CHIMU NRO. 936 URB. ZARATE STAND 35-36-37 - CRUCE CON VARA DE ORO",
    telefono: "970-130-813",
    horario: "De Lunes a Domingo de 9:30 a.m. a 7:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: "/images/puntoscanje/CARNICERIA-NARCISA.webp",
    urlmapa: "upload/Tqo7GI1G2rQh0qrkVUUH2hsaq9vhKvXBFAKtSkdT.png",
    url_tienda_jpg: "upload/qUPiOCypg7eYHkpu68GYUKhLtSGudII1SR2weN57.jpeg",
    url_tienda_webp: "upload/jaiL1xdfLljqjvQJa8lvUIS9jc0Dnori14BnQjK2.webp",
    latitud: "-12.025015",
    longitud: "-76.998228",
    estado: 1,
    id_seguimiento: "tienda-afiliada-san-juan-de-lurigancho-carniceria-narcisa",
    aceptareactivacion: 0,
  },
  {
    id: 16,
    tipo: "tienda afiliada",
    producto: "1,3",
    producto_pavo: "1",
    producto_cerdo: "2",
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "San Juan de Miraflores",
    tipo_ubicacion: "Lima",
    nombre: "COMERCIAL CELA",
    direccion: "Av. Jose Gabriel Charriarse Nro. 496 Zona A",
    telefono: "922-514-208",
    horario:
      "De Lunes a S\u00e1bado de 8:00 a.m. a 7:00 p.m. Domingo 8:00 am - 1:00 pm",
    restricciones:
      "Se atiende vale f\u00edsico y vale digital por pavo y cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tienda-SJM-CELA.webp",
    urlfoto: "/images/puntoscanje/Tienda-SJM-CELA.webp",
    urlmapa: "upload/SrR6BKrmvgG4MTrlWMYK7MUe3YJe9Sh56E8PoumQ.png",
    url_tienda_jpg: "upload/d10oI97XhfJ7GNY1AyW0Ocu9KFn5LkuyoiR7d95X.png",
    url_tienda_webp: "upload/KH3NdHjZ3D95SrMeWWAaVDjU4bhoQQ53livn5Zsr.webp",
    latitud: "-12.15506989",
    longitud: "-76.97251182",
    estado: 1,
    id_seguimiento: "tienda-afiliada-san-juan-de-miraflores-comercial-cela",
    aceptareactivacion: 1,
  },
  {
    id: 13,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "San Martin de Porres",
    tipo_ubicacion: "Lima",
    nombre: "LA REAL FAMILIA",
    direccion: "Mza. N Lote 09 Coo Santa Apolonia",
    telefono: "919-476-788",
    horario: "Lunes a s\u00e1bado de 8:30 am a 5:30 pm.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tienda-SMP-(Los%20olivos2)-Real-Familia.webp",
    urlfoto: "/images/puntoscanje/Tienda-SMP-(Los%20olivos2)-Real-Familia.webp",
    urlmapa: "upload/ky3PVR0FaAxIxympA2C8VcqLwWByggX6OEu1wA2y.png",
    url_tienda_jpg: "upload/AbIiWp2CetHEabIsllvcvEuQfLYMWouqPD8JeP4B.jpeg",
    url_tienda_webp: "upload/BhtWdcd3jBvGfpVgql9WjHxaZtqiYwG8FAXa9dL4.webp",
    latitud: "-12.004251",
    longitud: "-77.093795",
    estado: 1,
    id_seguimiento: "tienda-afiliada-los-olivos-apertem",
    aceptareactivacion: 0,
  },
  {
    id: 17,
    tipo: "tienda afiliada",
    producto: "1,3",
    producto_pavo: "1",
    producto_cerdo: "2",
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "San Martin de Porres",
    tipo_ubicacion: "Lima",
    nombre: "MEGAN FOX (JUAN ALVAREZ)",
    direccion: "Av. Martir Olaya 413 Zarumilla",
    telefono: "(01) 480 4724",
    horario:
      "De Martes a S\u00e1bado de 5:30 a.m. a 3:30 p.m. Domingo de 5:30 am- 3:30 pm",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo y cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tienda-SMP-Megan-Fox.webp",
    urlfoto: "/images/puntoscanje/Tienda-SMP-Megan-Fox.webp",
    urlmapa: "upload/4dZFYUxU0qLTJWzz5vlQLKjZJ8hbx4wV7P8kjk7X.png",
    url_tienda_jpg: "upload/PnYqapTlMvRZ95GH7DZpGdaRtHbH7LuTc48TdWAU.png",
    url_tienda_webp: "upload/QngTsSAmTGYq8ha56P43SnXVsq4SyI1gde4Tb9aD.webp",
    latitud: "-12.0345608",
    longitud: "-77.047624",
    estado: 1,
    id_seguimiento:
      "tienda-afiliada-san-martin-de-porres-megan-fox-juan-alvarez",
    aceptareactivacion: 0,
  },
  {
    id: 84,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "San Martin de Porres",
    tipo_ubicacion: "Lima",
    nombre: "GRANJA 34 E.I.R.L.",
    direccion: "Jr. Iquitos 347",
    telefono: "967-801-800",
    horario:
      "Lunes  a S\u00e1bado de 7:30 a.m. a 3:00 p.m.  y Domingo de 8:00 am a 2:00 pm",
    restricciones:
      "Se atiende vale f\u00edsico y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/092hPhTYPbTSdLqRB5rt0rt2oqZA9XHtYHOgKwKA.png",
    url_tienda_jpg: "upload/u92tj7xpooUIEwmRUOwBj8h7H9YSDj6g4IbJkUTX.jpeg",
    url_tienda_webp: "upload/V8lLnRND94ryGeq95QDB2KH2jyaEim17wRyDnyVd.webp",
    latitud: "-12.0284285",
    longitud: "-77.0844241",
    estado: 1,
    id_seguimiento: "tienda-afiliada-san-martin-de-porres-granja-34",
    aceptareactivacion: 0,
  },
  {
    id: 21,
    tipo: "multimarket",
    producto: "1,3",
    producto_pavo: "1",
    producto_cerdo: "2",
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "San Miguel",
    tipo_ubicacion: "Lima",
    nombre: "ALBEMARCO S.A",
    direccion: "Av. Elmer Faucett N\u00b0 579",
    telefono: "952-993-871",
    horario: "De Lunes a Domingo de 8:00 a.m. a 7:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo y cerdo. Se atiende vale f\u00edsico por pavo y vale digital por pavo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/MMK-FAUCETT.webp",
    urlfoto: "/images/puntoscanje/MMK-FAUCETT.webp",
    urlmapa: "upload/VXdUXO3NtHP97v2DX4d8vE2fpGgAhGgTES1sMwYF.png",
    url_tienda_jpg: "upload/REFXi91Ssa3ZH2fMTK7IeC3FUJVnSsnznXjj4lzg.png",
    url_tienda_webp: "upload/LzZNndTqygpI4KtSWXPW2mVU0K0Q7TeljamIEvxu.webp",
    latitud: "-12.06367081",
    longitud: "-77.09745264",
    estado: 1,
    id_seguimiento: "multimarkert-san-miguel-albemarco-sa",
    aceptareactivacion: 0,
  },
  {
    id: 19,
    tipo: "multimarket",
    producto: "1,3",
    producto_pavo: "1",
    producto_cerdo: "2",
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Surco",
    tipo_ubicacion: "Lima",
    nombre: "ALBEMARCO S.A",
    direccion: "Av. Caminos Del Inca N\u00b01012",
    telefono: "(01) 4194360",
    horario: "De Lunes a Domingo de 8:00 a.m. a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/MMK-CAMINOS.webp",
    urlfoto: "/images/puntoscanje/MMK-CAMINOS.webp",
    urlmapa: "upload/81fE8JQ4juhwj6uBv9Jy32957zao2Q4NSjMKAZyO.png",
    url_tienda_jpg: "upload/FJS7igr3zJgRqQAzgt8AxPLb3TXOcQMmx1ABkxiM.png",
    url_tienda_webp: "upload/m3Qz1Ceo7nl0P3EgHdRh7ETfpdd3Xwayu5QnlonN.webp",
    latitud: "-12.12085979",
    longitud: "-76.98795934",
    estado: 1,
    id_seguimiento: "multimarkert-surco-albemarco-sa-caminos",
    aceptareactivacion: 0,
  },
  {
    id: 20,
    tipo: "multimarket",
    producto: "1,3",
    producto_pavo: "1",
    producto_cerdo: "2",
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Surco",
    tipo_ubicacion: "Lima",
    nombre: "ALBEMARCO S.A",
    direccion: "Av. La Encalada N\u00b0 464",
    telefono: "952-994-156",
    horario: "De Lunes a Domingo de 8:00 a.m. a 7:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo y cerdo. Se atiende vale f\u00edsico por pavo y vale digital por pavo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/MMK-ENCALADA.webp",
    urlfoto: "/images/puntoscanje/MMK-ENCALADA.webp",
    urlmapa: "upload/vHqtJsU4ptkPiZpkge1n4eMvr4iTrzB5rzu5f0TA.png",
    url_tienda_jpg: "upload/I5WhUcra5gij1a1S1SbCY8NwG2z6afbkheLtkMDj.png",
    url_tienda_webp: "upload/n0inU5gCnqgbUMwkHRwrXqEhbqxe8Q2AJzmPOwML.webp",
    latitud: "-12.11030244",
    longitud: "-76.97281696",
    estado: 1,
    id_seguimiento: "multimarkert-surco-albemarco-sa-encala",
    aceptareactivacion: 0,
  },
  {
    id: 22,
    tipo: "multimarket",
    producto: "1,3",
    producto_pavo: "1",
    producto_cerdo: "2",
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Surquillo",
    tipo_ubicacion: "Lima",
    nombre: "ALBEMARCO S.A",
    direccion: "Av. Republica De Panama N\u00b0 4299",
    telefono: "952-993-645",
    horario: "De Lunes a Domingo de 6:30 a.m. a 10:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo y cerdo. Se atiende vale f\u00edsico por pavo y vale digital por pavo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/MMK%20SURQUILLO.webp",
    urlfoto: "/images/puntoscanje/MMK-SURQUILLO.webp",
    urlmapa: "upload/LYr8xqkRXEdEv2X3bIfkiAxu63Vu0nlK3tEHd1lx.png",
    url_tienda_jpg: "upload/K8BfWiRvUhwrwVDssQt2sqtnK2Z0A2IaE6MOP43c.png",
    url_tienda_webp: "upload/bwgziQgPbHrnngiPlETN6W9cgKBjhA2hjfCKFptF.webp",
    latitud: "-12.10768217",
    longitud: "-77.01834557",
    estado: 1,
    id_seguimiento: "multimarkert-surquillo-albemarco-sa",
    aceptareactivacion: 0,
  },
  {
    id: 18,
    tipo: "tienda afiliada",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Villa el Salvador",
    tipo_ubicacion: "Lima",
    nombre: "GRUPO EULALIA",
    direccion: "Mza.I Lote.17 Sector 2 Grupo 5, Villa El Salvador",
    telefono: "(01) 307 5572",
    horario: "De Lunes a S\u00e1bado de 8:30 a.m. a 4:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tienda-VES-Grupo-Eulalia.webp",
    urlfoto: "/images/puntoscanje/Tienda-VES-Grupo-Eulalia.webp",
    urlmapa: "upload/AYGSIgcpeNu6cRMc0ORHsFD0KG8PWNdvdzxpxnZA.png",
    url_tienda_jpg: "upload/2RbgjcWQ4cPpbBhMcYp0untw6L9Uq70eclZUqaUN.png",
    url_tienda_webp: "upload/dY5tRrA2FFNLohxsHqYp3QgzV0MFcYuhLedg9izC.webp",
    latitud: "-12.21143652",
    longitud: "-76.93389081",
    estado: 1,
    id_seguimiento: "tienda-afiliada-villa-el-salvador-grupo-eulalia",
    aceptareactivacion: 0,
  },
  {
    id: 93,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Abancay",
    tipo_ubicacion: "provincia",
    nombre: "GRUPO AVEANDES E&W S.A.C.",
    direccion: "Av. Villa El Sol S/N MZ.H LT1-Abancay",
    telefono: "933-606-542 / 942-558-005",
    horario:
      "De Lunes a Viernes de 9:00 a.m. a 1:00 p.m. y de 4:00 p.m.a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/JbIZ4r6JluV0jOmZIH8tXaALCUeKuCR1zVqoTqN3.png",
    url_tienda_jpg: null,
    url_tienda_webp: null,
    latitud: "-13.638499",
    longitud: "-72.890519",
    estado: 1,
    id_seguimiento: "DAP-Abancay-grupo-aveandes",
    aceptareactivacion: 0,
  },
  {
    id: 23,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Arequipa",
    tipo_ubicacion: "provincia",
    nombre: "CEPCO E.I.R.L.",
    direccion:
      "Av. Daniel Alcides Carri\u00f3n 168. Cercado (frente a la Facultad De Medicina de la Universidad San Agustin)",
    telefono: "958-201-527 / (054) 224587 / 998998493",
    horario: "De Lunes a S\u00e1bado de 7:00 a.m. a 1:30 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo y cerdo. Atenci\u00f3n por Cerdo 23, 24, 29 y 30 de Diciembre. Disponibilidad sujeta a stock. Cada punto autorizado de canje define sus propios precios de venta al consumidor.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Arequipa-Av-Daniel-Alcides-Carri\u00f3n-168-Cercado.webp",
    urlfoto:
      "/images/puntoscanje/Arequipa-Av-Daniel-Alcides-Carrion-168-Cercado.webp",
    urlmapa: "upload/3I7fA9EGBLn2H6crIMpyCHm9MMhfUg5uEOPE7app.png",
    url_tienda_jpg: "upload/f0GmESDZ69XVIZJ8LNn2ZgdVroKoa1KD0SvUr9BK.png",
    url_tienda_webp: "upload/GAIZFb2VDElagaQab6Z4ZpHXf6hlR2P1IPWVrEQr.webp",
    latitud: "-16.41292525",
    longitud: "-71.53529665",
    estado: 1,
    id_seguimiento: "distribuidor-autorizado-arequipa-cepco-eirl",
    aceptareactivacion: 0,
  },
  {
    id: 81,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico",
    tipovale_uno: "fisico",
    tipovale_dos: null,
    ubicacion: "Cajamarca",
    tipo_ubicacion: "provincia",
    nombre: "MARIA ROSA TERAN GUEVARA",
    direccion: "Jr. Puno 376, Cajamarca",
    telefono: "976363290",
    horario: "Lunes a Viernes 9:00 a.m. a 12:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo. No se atiende vale por cerdo. No se atiende vale digital. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/xbyNPtcipJUv8QdW9eXHql0VJomyVy6g7n5iNjNQ.png",
    url_tienda_jpg: "upload/a030HAs7TVTftCh2zKfQ5RI9PACYYXbV2HgrZsIB.jpeg",
    url_tienda_webp: "upload/Sjsom3FkqMTTC2hvBamJDkOGqQTo6gneWxzur9LG.webp",
    latitud: "-7.150108",
    longitud: "-78.524480",
    estado: 1,
    id_seguimiento:
      "distribuidor-autorizado-cajamarca-maria-rosa-teran-guevara",
    aceptareactivacion: 0,
  },
  {
    id: 25,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Ca\u00f1ete",
    tipo_ubicacion: "provincia",
    nombre: "CONSORCIO 3C PLAYA - MALA",
    direccion: "Jr. Marchand 505 Mala, Ca\u00f1ete",
    telefono: "970-556-950",
    horario:
      "Lunes a Viernes 8:30 a.m. a 12:30 p.m.  y de 3:30 p.m. a 5:30 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Canete-Jr-Marchand-505%20Mala-Canete.webp",
    urlfoto: "/images/puntoscanje/Canete-Jr-Marchand-505-Mala-Canete.webp",
    urlmapa: "upload/og0FVgOQ7R31K2ievHGGUSlUxJc7BmLDHeDKd5JH.png",
    url_tienda_jpg: "upload/iQx2S9yN0uCEqQQgenQyiDeXByDk9UBTmHygIpqZ.png",
    url_tienda_webp: "upload/WKfZCcPcq7xkuqO6j27zhK3YTZixIKAj2rmY9wD4.webp",
    latitud: "-12.6586615",
    longitud: "-76.6371794",
    estado: 1,
    id_seguimiento:
      "distribuidor-autorizado-ca\u00f1ete-consorcio-3c-playa-mala",
    aceptareactivacion: 0,
  },
  {
    id: 26,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Chanchamayo",
    tipo_ubicacion: "provincia",
    nombre: "DISTRIBUIDORA  y NEGOCIACIONES ACOSTA S.A.C",
    direccion:
      "Calle Sor Albina MZ B - LOTE 05 URB. Pampa del Carmen - Chanchamayo, Jun\u00edn",
    telefono: "964-635- 644",
    horario:
      "Lunes a Viernes 9:00 a.m. a 1:00 p.m.  y de 4:00 p.m. a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/La-Merced-Calle-Sor-Albina-Maz-B-Lot-05-Urb-Pampa-del-Carmen-Chanchamayo.webp",
    urlfoto: "/images/puntoscanje/tienda-chanchamayo.webp",
    urlmapa: "upload/wQbCsZQibafiKLA9lLTjbdizrHKueO0tuJGIaZDb.png",
    url_tienda_jpg: "upload/txv0Es7U57LHqLrMS60YYHy7GJAMagfalJaNLtsc.png",
    url_tienda_webp: "upload/W4xVDJeTN62Wx0l3AQtQ7l52wxStnz6aKqfIj4Ji.png",
    latitud: "-11.05395135",
    longitud: "-75.32736633",
    estado: 1,
    id_seguimiento:
      "distribuidor-autorizado-chanchamayo-distribuidora-y-negociaciones-acosta-sac",
    aceptareactivacion: 0,
  },
  {
    id: 27,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Chiclayo",
    tipo_ubicacion: "provincia",
    nombre: "Tienda Chimu",
    direccion: "Av. Saenz Pe\u00f1a 1328",
    telefono: "074-227234",
    horario:
      "Lunes a S\u00e1bado 7:00 a.m. a 1:00 p.m.  y de 4:00 p.m. a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Chiclayo-Estadio-EliasAguirre-Av-del-Deporte-180.webp",
    urlfoto:
      "/images/puntoscanje/Chiclayo-Estadio-EliasAguirre-Av-del-Deporte-180.webp",
    urlmapa: "upload/CpccdrjKDY6eUsKq8nGZT1K63L3FeTcyXRDs3egI.png",
    url_tienda_jpg: "upload/rZJ2HFYJzJzVh1YuN2C3Hr6BII69bSFiQHbuAHLy.png",
    url_tienda_webp: "upload/QIcYZuSZmv7G1hfgqoE8SIMBkS64fxrBuzbrK2F3.webp",
    latitud: "-6.767676",
    longitud: "-79.835474",
    estado: 1,
    id_seguimiento:
      "distribuidor-autorizado-chiclayo-multiservicios-byg-amigo-eirl",
    aceptareactivacion: 0,
  },
  {
    id: 45,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Chimbote (Santa)",
    tipo_ubicacion: "provincia",
    nombre: "PERU CARNES SAC",
    direccion: "Av. Pardo 1570 PJ Miramar Bajo, Chimbote",
    telefono: "969-700-879",
    horario:
      "Lunes a Viernes 9:00 a.m. a 1:00 p.m.  y de 4:00 p.m. a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Chimbote-Av-Pardo-1570-Miramar-Bajo-Chimbote.webp",
    urlfoto:
      "/images/puntoscanje/Chimbote-Av-Pardo-1570-Miramar-Bajo-Chimbote.webp",
    urlmapa: "upload/Nz8u896Hin9h2KgpF92cMnSm9deyL20Qia43lQBc.png",
    url_tienda_jpg: "upload/cFz3oyw0FTx1zeqNwYjMG9RRy5lYHeyxVAzVkoxp.png",
    url_tienda_webp: "upload/fr45nRM5HIwXE6FNU9sAZ508pMTgLCmuMuCkrweK.webp",
    latitud: "-9.078944597",
    longitud: "-78.58116174",
    estado: 1,
    id_seguimiento: "distribuidor-autorizado-santa-peru-carnes-sac",
    aceptareactivacion: 0,
  },
  {
    id: 28,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Chincha",
    tipo_ubicacion: "provincia",
    nombre: "IMPORTACIONES SANDDORIA S.A.C.",
    direccion: "Carr. Panamericana Sur # 1719 Sunampe Chincha",
    telefono: "977-597-336",
    horario: "Lunes a Viernes 8:00 a.m. a 1:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Chincha-Av-Panamericana-Nro-1719-Sunampe.webp",
    urlfoto:
      "/images/puntoscanje/Chincha-Av-Panamericana-Nro-1719-Sunampe.webp",
    urlmapa: "upload/a9d5uvlVEAniFlrdTVmn9LxhKXugL3vgmx5xoR7d.png",
    url_tienda_jpg: "upload/pYcLX8TRBG6acRdoAQnzW0rrVIRkL2Dz8Bt8SHHi.png",
    url_tienda_webp: "upload/qv5ytituYST8MXKBvpUmnOwSSFVRI3rBw6ipJ3As.webp",
    latitud: "-13.4110602709974",
    longitud: "-76.1609913292517",
    estado: 1,
    id_seguimiento:
      "distribuidor-autorizado-chincha-importaciones-sanddoria-sac",
    aceptareactivacion: 0,
  },
  {
    id: 30,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Cusco",
    tipo_ubicacion: "provincia",
    nombre: "CONSORCIO ORION CUSCO S.R.L.",
    direccion:
      "Av. Via Expresa Mza. E Lote. 7 Urb. Parque Industrial Cusco Wanchaq",
    telefono: "984-766-498",
    horario: "Lunes a Viernes 9:00 a.m. a 1:00 p.m. y de 4:00 p.m. a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico y digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Cusco-Av-V\u00eda-Expresa-Mza-E-Lote-7-Urb-Parque-Industrial.webp",
    urlfoto:
      "/images/puntoscanje/Cusco-Av-Via-Expresa-Mza-E-Lote-7-Urb-Parque-Industrial.webp",
    urlmapa: "upload/bXzeknAgfWDFQ0oGJh9ciRnTO5MVOnEwPQMAmdO1.png",
    url_tienda_jpg: "upload/KO3fHGV2EhgpAPtJx76Ef2A8HE22qUpXpf46jiak.jpeg",
    url_tienda_webp: "upload/sxMW3jkKhZvymxpewHncrQzDa4bUsDACfNFgZEjO.jpeg",
    latitud: "-13.53387236",
    longitud: "-71.94329623",
    estado: 1,
    id_seguimiento: "distribuidor-autorizado-cusco-consorcio-orion-cusco-srl",
    aceptareactivacion: 0,
  },
  {
    id: 31,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Huamanga",
    tipo_ubicacion: "provincia",
    nombre: "AGROINDUSTRIAS QUISPE E.I.R.L.",
    direccion:
      "Av. Ram\u00f3n Castilla # 876 int. B, San Juan Bautista, Ayacucho",
    telefono: "942-206-150",
    horario: "Lunes a viernes de 9:00 am a 13:00 pm.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Huamanga-Av-Ram\u00f3n-Castilla-876-int-B-San-Juan.webp",
    urlfoto:
      "/images/puntoscanje/Huamanga-Av-Ramon-Castilla-876-int-B-San-Juan.webp",
    urlmapa: "upload/mtlT7cE7vnJRZeMyXtliflV7ZYiWpkwglFJXyola.png",
    url_tienda_jpg: "upload/OGHkUrqIaMJsdGcFNBxYQEyXAKsIYhas41Y3vywN.png",
    url_tienda_webp: "upload/lXcZJEsFYuxoONPtbf2uKsAQByP12ptK3pwqHvgg.webp",
    latitud: "-13.1661877049813",
    longitud: "-74.2149121879761",
    estado: 1,
    id_seguimiento:
      "distribuidor-autorizado-huamanga-agroindutrias-quispe-eirl",
    aceptareactivacion: 0,
  },
  {
    id: 32,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Huancayo",
    tipo_ubicacion: "provincia",
    nombre: "MAPELLI & ACOSTA DISTRIBUIDORA Y NEGOCIACIONES WANKA SAC",
    direccion:
      "Av. Miguel Grau S/N, El Tambo (Frente al Estadio de Sa\u00f1os Grande)",
    telefono: "933867243",
    horario: "Lunes a Viernes 9:00 a.m. a 1:00 p.m. y de 4:00 p.m. a 5:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico y digital por pavo y cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Huancayo-JR-MIGUEL-GRAU-SN-EL-TAMBO-HUANCAYO-FRENTE-AL-ESTADIO-DE-SANOS-GRANDE.webp",
    urlfoto: "/images/puntoscanje/tienda-huancayo.webp",
    urlmapa: "upload/w6MTF6MvlTfdFy6pJimdhIHPTVj2El6yJcXLmtAZ.png",
    url_tienda_jpg: "upload/fNSJZ9exSG2d69NdTvHcYOg5xBPHIW2Wes2viRMG.jpeg",
    url_tienda_webp: "upload/ytCY5yLkwdiEPXzYLYwptGKtJQNaxE8fpeomHZgO.jpeg",
    latitud: "-12.017416",
    longitud: "-75.225841",
    estado: 1,
    id_seguimiento:
      "distribuidor-autorizado-huancayo-mapelli-acosta-distribuidora-y-negociaciones-wanka-sac",
    aceptareactivacion: 0,
  },
  {
    id: 33,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Huanuco",
    tipo_ubicacion: "provincia",
    nombre: "AUTOSERVICIOS DON PEDRO SRL",
    direccion: "Jr. Leoncio Prado N\u00b0 1003",
    telefono: "(062) 517505",
    horario: "Lunes a Viernes 9:00 a.m. a 1:00 p.m. y de 4:00 p.m. a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo. No se atiende vale por cerdo. No se atiende vale digital. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Huanuco-Jr-Leoncio-Prado-N\u00b0-1003-Huanuco.webp",
    urlfoto: "/images/puntoscanje/Huanuco-Jr-Leoncio-Prado-N-1003-Huanuco.webp",
    urlmapa: "upload/pWhlnuEADDcpAJZzBD4syRpScTC8y5wkxFbiaJyB.png",
    url_tienda_jpg: "upload/bhYhuO60gZ77beVVGe7ideZHLBsbt4TW7nCo5UXU.png",
    url_tienda_webp: "upload/17l1VuxXr9pRLcmoHByPJ8TeO78NTOsDm3o9QkJf.webp",
    latitud: "-9.92808628431633",
    longitud: "-76.2446191557806",
    estado: 1,
    id_seguimiento:
      "distribuidor-autorizado-huanuco-autoservicio-don-pedro-srl",
    aceptareactivacion: 0,
  },
  {
    id: 96,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Huaraz",
    tipo_ubicacion: "provincia",
    nombre: "DISTRIBUCIONES MERCONOR SAC",
    direccion: "Barrio de Tacllan Car. Huaraz-Pativilca Sector SUR KM 2",
    telefono: "973-700-007",
    horario: "Lunes a Viernes 9:00 a.m. a 1:00 p.m. y de 4:00 p.m. a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico y digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/5lJZmmOz9XGva6fMRB9RLAHs9FcOuMQ5fbjtBD2C.png",
    url_tienda_jpg: "upload/vf0omIt0ShAuuzUSUEovrrc7mJVynSC8TA1wuvdh.jpeg",
    url_tienda_webp: "upload/N13vkDBHdNyv5SJdlUmcZ7JpiPKSECfC2jD0YoEp.jpeg",
    latitud: "-9.542445800000001",
    longitud: "-77.5311297",
    estado: 1,
    id_seguimiento: "DAP-Huaraz- DISTRIBUCIONES-MERCONOR-SAC",
    aceptareactivacion: 0,
  },
  {
    id: 35,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Ica",
    tipo_ubicacion: "provincia",
    nombre: "LOGISTICA DEL SUR S.R.L",
    direccion: "Av. JJ.Elias # 451",
    telefono: "995-119-455 / (056) 218203",
    horario: "Lunes a Viernes 8:00 a.m. a 12:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico y digital por pavo y cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Ica-Av-JJ-Elias-451.webp",
    urlfoto: "/images/puntoscanje/Ica-Av-JJ-Elias-451.webp",
    urlmapa: "upload/KnlIMFe6nq3UjeAuLeJXU460aSgw9Jzv8JrPdTmU.png",
    url_tienda_jpg: "upload/FAjVZZuJ4FB2Y7Ir2Yyh6mGUH4YtwHSdbH92cQpM.png",
    url_tienda_webp: "upload/VHpQ1j06ZNZrVQS2VlXuFN2dsGJSgxGuwmgMqj4q.webp",
    latitud: "-14.06806639",
    longitud: "-75.73249025",
    estado: 1,
    id_seguimiento: "distribuidor-autorizado-ica-logistica-del-sur-srl",
    aceptareactivacion: 0,
  },
  {
    id: 100,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Iquitos (Maynas)",
    tipo_ubicacion: "provincia",
    nombre: "SERVICIOS GENERALES Y COMERCIALIZADORA IRMITA EIRL",
    direccion: "Calle Jose Galvez 968  (a 2 cuadras del Cementerio General)",
    telefono: "965-975-234",
    horario: "Lunes a Viernes 8:00 a.m. a 1:00 p.m.",
    restricciones: "-",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/IG8m3WXJksPN9us4ERqJQeApg9tMxHYfQ1TO56s2.png",
    url_tienda_jpg: null,
    url_tienda_webp: null,
    latitud: "-3.7564276",
    longitud: "-73.2580091",
    estado: 1,
    id_seguimiento: "DAP- IRMITA - IQUITOS",
    aceptareactivacion: 0,
  },
  {
    id: 44,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Juliaca (San Rom\u00e1n)",
    tipo_ubicacion: "provincia",
    nombre: "AVES DEL SUR",
    direccion: "Av. Tacna 420, Juliaca, San Roman, Puno",
    telefono: "974-554-752",
    horario: "Lunes a Viernes 8:00 a.m. a 1:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/San-Roman-(Juliaca)-Av-Tacna-Nro-420--Juliaca-San-Roman-Puno.webp",
    urlfoto:
      "/images/puntoscanje/San-Roman-(Juliaca)-Av-Tacna-Nro-420--Juliaca-San-Roman-Puno.webp",
    urlmapa: "upload/HwEAW4V4YfGeEyev5E2YD1qxAfXjXDnmAshGH5Dy.png",
    url_tienda_jpg: "upload/ViT6deJibsq4ugEvWWVUNT8Y0Rn0qovBtsARfUzr.png",
    url_tienda_webp: "upload/fr7dD5w59I50A8Lkzt7HPnIBY3j08sFJDIO98eUL.webp",
    latitud: "-15.5025536866002",
    longitud: "-70.1262494364646",
    estado: 1,
    id_seguimiento: "distribuidor-autorizado-san-roman-aves-del-sur",
    aceptareactivacion: 0,
  },
  {
    id: 77,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Piura",
    tipo_ubicacion: "provincia",
    nombre: "INVERSIONES LUDIMARC S.A.C.",
    direccion: "OTR.Zona Industrial Mza. 223 Lote. 6 Z.I. - Piura",
    telefono: "985106941",
    horario:
      "De Lunes a Viernes de 9:00 a.m. a 1:00 p.m. y de 4:00 p.m.a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo, vale f\u00edsico por cerdo y vale digital por pavo. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/uwej35qwDNWBcbGf7Ou8XrH8ivDRjRH40gvBT20h.png",
    url_tienda_jpg: "upload/THVs4ZNozPAfeR1SZm321lW00yktsqjQNFgaED99.jpeg",
    url_tienda_webp: "upload/VWEfO9myvACVYOMuJeY6PcvPlgWdYJyVBJVwwkRe.webp",
    latitud: null,
    longitud: null,
    estado: 1,
    id_seguimiento: "distribuidor-autorizado-piura-inversiones-ludimarc-sac",
    aceptareactivacion: 0,
  },
  {
    id: 29,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Pucallpa (Coronel Portillo)",
    tipo_ubicacion: "provincia",
    nombre: "DISTRIBUIDORA VOLCAN E.I.R.L",
    direccion:
      "Jr. Guillermo Sisley Nro. 504 Int. a Coronel Portillo, Pucallpa, Ucayali",
    telefono: "949-365-316",
    horario: "Lunes a Viernes 9:00 a.m. a 1:00 p.m. y de 4:00 p.m. a 5:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Coronel-Portillo-JR-Guillermo-Sisley-Nro-504-Int-a.webp",
    urlfoto:
      "/images/puntoscanje/Coronel-Portillo-JR-Guillermo-Sisley-Nro-504-Int-a.webp",
    urlmapa: "upload/Wv81Of71uiywKDZdtB4dHjF7SGj801GQszrdrygE.png",
    url_tienda_jpg: "upload/F6ETkxFRqJrj3onNuRaKKHX5OdgkZTyK3AeKoc4n.png",
    url_tienda_webp: "upload/UVl7meK8En5bK3B3n48xdIw4JsNujOL3h07BZldk.webp",
    latitud: "-8.376441281",
    longitud: "-74.54078535",
    estado: 1,
    id_seguimiento:
      "distribuidor-autorizado-coronel-portillo-distribuidora-volcan-eirl",
    aceptareactivacion: 0,
  },
  {
    id: 42,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Puno",
    tipo_ubicacion: "provincia",
    nombre: "INDUSTRIA ALIMENTARIA NEGOLATINA SCRL",
    direccion: "Av. Floral Nro. 940, Barrio Vallecito ( camino a la UNA )",
    telefono: "954-160-194",
    horario: "Lunes a Viernes 9:00 a.m. a 1:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Puno-Av-Floral-Nro-940-Barrio-Vallecito.webp",
    urlfoto: "/images/puntoscanje/Puno-Av-Floral-Nro-940-Barrio-Vallecito.webp",
    urlmapa: "upload/ER6n4yxWJn0kzFd7bCmnQpj7Vr1EKApLsgs77whJ.png",
    url_tienda_jpg: "upload/ksVzHdyqVEDZNCo0sQoTGQNpN9QGrzMAetuvbhR2.jpeg",
    url_tienda_webp: "upload/zQcsBbtaeJlc9sD5W7ZSw3EfcHI1g0YPB1Jwvduh.webp",
    latitud: "-15.82974491",
    longitud: "-70.01824792",
    estado: 1,
    id_seguimiento:
      "distribuidor-autorizado-industria-alimentaria-negolatina-scrl",
    aceptareactivacion: 0,
  },
  {
    id: 46,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Tacna",
    tipo_ubicacion: "provincia",
    nombre: "LA GENOVESA AGROINDUSTRIAS S.A",
    direccion: "Mza. I Lote. 9B Parque Industrial",
    telefono: "979-406-154",
    horario: "Lunes a Viernes 8:00 a.m. a 1:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tacna-Mza-I-Lote-9B-Parque-Industrial.webp",
    urlfoto: "/images/puntoscanje/Tacna-Mza-I-Lote-9B-Parque-Industrial.webp",
    urlmapa: "upload/q4zwzrTgCOnDV58LJ6DIQwedmreRtCeQaQQ0StAV.png",
    url_tienda_jpg: "upload/slPswYkpesYkG0fvZHpn5a7aJlhuJbYhAMGqNQ1U.png",
    url_tienda_webp: "upload/Vf3Hb9dpJk18sTtu2bkRWVZnvwqGquakmNb1QLOX.webp",
    latitud: "-17.9963548626788",
    longitud: "-70.240317324544",
    estado: 1,
    id_seguimiento: "distribuidor-autorizado-la-genovesa-agroindustrias-sa",
    aceptareactivacion: 0,
  },
  {
    id: 43,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Tarapoto",
    tipo_ubicacion: "provincia",
    nombre: "GRUPO ALIMENTOS",
    direccion:
      "Jr. Leticia N\u00b0 430, Morales (a 1.5 cuadras de la Casa Blanca)",
    telefono: "042-604500",
    horario: "Lunes a Viernes 9:00 a.m. a 1:00 p.m. y de 4:00 p.m. a 5:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Tarapoto-Jr-Leticia-N\u00b0-430-Morales-(A-1).webp",
    urlfoto:
      "/images/puntoscanje/Tarapoto-Jr-Leticia-Nro-430-Morales-(A-1).webp",
    urlmapa: "upload/vkuPJ170dc11QNJoB16h0NgcDmnGfrmi2sj9QJ4Z.png",
    url_tienda_jpg: "upload/HLt6abycVuMUsN6q9Mo8CCcb5YS2Zsq2SSuUHVmh.jpeg",
    url_tienda_webp: "upload/FLmAVdvfoR3vnZLbxfxeEFXAOLfTDntKBS2FkjTd.jpeg",
    latitud: "-6.4762185",
    longitud: "-76.3836853",
    estado: 1,
    id_seguimiento: "distribuidor-autorizado-san-martin-grupo-alimentos",
    aceptareactivacion: 0,
  },
  {
    id: 38,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Tingo Mar\u00eda (Leoncio Prado)",
    tipo_ubicacion: "provincia",
    nombre: "MERY Y MARY",
    direccion: "Av. Antonio Raymondi 1150 Leoncio Prado, Tingo Maria",
    telefono: "938-629-005 / 933-348-265",
    horario: "Lunes a Viernes 8:00 a.m. a 1:00 p.m. y de 4:00 p.m. a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico y digital por pavo. No se atiende vale por cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje//Leoncio-Prado-(Tingo-Maria)-Av-Antonio-Raymondi-1150.webp",
    urlfoto:
      "/images/puntoscanje//Leoncio-Prado-(Tingo-Maria)-Av-Antonio-Raymondi-1150.webp",
    urlmapa: "upload/GXk82VwvWUAntbNvootXbNor2SV78GOSZTp7caFm.png",
    url_tienda_jpg: "upload/bUUkmx5VuJUl3zozPvizs0PN8Pm8P7l228Jno6yM.jpeg",
    url_tienda_webp: "upload/4r210AQ8pJJyQNWAs2jJkujWmc0iJgOj1l8HA2UJ.webp",
    latitud: "-12.0591198693572",
    longitud: "-77.018670319345",
    estado: 1,
    id_seguimiento: "distribuidor-autorizado-leoncio-prado-mary-y-mary",
    aceptareactivacion: 0,
  },
  {
    id: 50,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Trujillo",
    tipo_ubicacion: "provincia",
    nombre: "CHIMU AGROPECUARIA",
    direccion:
      "Av. Prolongaci\u00f3n Vallejo Mz. E Lote 29, Urb. Ingenier\u00eda  ( al costado del UPAO )",
    telefono: "044 - 266104",
    horario:
      "Lunes a S\u00e1bado 7:00 a.m. a 1:00 p.m. y de 4:00 p.m. a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico y digital por pavo y cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Trujillo-Av-Prolongacion-Vallejo-Mz-E-Lote-29-Urb-Ingenieria.webp",
    urlfoto:
      "/images/puntoscanje/Trujillo-Av-Prolongacion-Vallejo-Mz-E-Lote-29-Urb-Ingenieria.webp",
    urlmapa: "upload/A69w2doOZ8UUJDTFKNeBdXq2YmFp7UzMXanq7bfT.png",
    url_tienda_jpg: "upload/htQbFei02PpN29sAZ7AlZ5lTCdGeBFxB4DSXQQGZ.png",
    url_tienda_webp: "upload/eEZ3AFOMoUC15wkHTZDL7AgJHjhhBm0WLzpNQX3E.webp",
    latitud: "-8.12781775795681",
    longitud: "-79.0302765421275",
    estado: 1,
    id_seguimiento:
      "distribuidor-autorizado-trujillo-chimu-agropecuaria-vallejo",
    aceptareactivacion: 0,
  },
  {
    id: 51,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Trujillo",
    tipo_ubicacion: "provincia",
    nombre: "CHIMU AGROPECUARIA",
    direccion: "Av. Larco 1357, Urb. La Merced",
    telefono: "044 - 374748",
    horario:
      "Lunes a S\u00e1bado 7:00 a.m. a 1:00 p.m. y de 4:00 p.m. a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico y digital por pavo y cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3:
      "https://www.san-fernando.com.pe/images/puntoscanje/Trujillo-Av-Larco-1357-Urb-La-Merced.webp",
    urlfoto: "/images/puntoscanje/Trujillo-Av-Larco-1357-Urb-La-Merced.webp",
    urlmapa: "upload/ujdvpmjswwMBf2pwHBvUfjXpndIN0joTkjP15pDb.png",
    url_tienda_jpg: "upload/jVgw6oT3kRUed3man4jXTV457QRfwHDmGJMe3FDG.png",
    url_tienda_webp: "upload/r9JogMXhLBnG10pnPykRL8ffW837LcEVBm2Oe8a7.webp",
    latitud: "-8.12660719647506",
    longitud: "-79.0405198099253",
    estado: 1,
    id_seguimiento: "distribuidor-autorizado-trujillo-chimu-agropecuaria-larco",
    aceptareactivacion: 0,
  },
  {
    id: 98,
    tipo: "distribuidor autorizado",
    producto: "1",
    producto_pavo: "1",
    producto_cerdo: null,
    tipovale: "fisico,digital",
    tipovale_uno: "fisico",
    tipovale_dos: "digital",
    ubicacion: "Trujillo",
    tipo_ubicacion: "provincia",
    nombre: "Chimu agropecuaria - Huanchaco",
    direccion:
      "Prolongaci\u00f3n Av. F\u00e1tima S/N - La Encalada (a 3 cuadras de Real Plaza Trujillo)",
    telefono: null,
    horario:
      "Lunes a S\u00e1bado 7:00 a.m. a 1:00 p.m. y de 4:00 p.m. a 6:00 p.m.",
    restricciones:
      "Se atiende vale f\u00edsico por pavo y vale digital por pavo y cerdo. Cada punto autorizado de canje define sus propios precios de venta al consumidor. Disponibilidad sujeta a stock.",
    urlfoto3: null,
    urlfoto: null,
    urlmapa: "upload/MmEiUQ0PkvBMM5U9SuFVwn4Z8R6VAqqRwsrNu50m.png",
    url_tienda_jpg: null,
    url_tienda_webp: "upload/dkmzoVLeEMbC62LQORwZ98PNEr86PCZhTi96b3MP.png",
    latitud: "-8.1318722",
    longitud: "-79.03167719999999",
    estado: 1,
    id_seguimiento: "distribuidor-autorizado-chimu-huanchaco-la-encalada",
    aceptareactivacion: 0,
  },
];
